### ISSUE TITLE
Package name not consistent and having a CORS issue

### ISSUE THREAD

**Issue by ruieloi** [Oriflame/backstage-plugins#100]
First of all, great idea and work. I really think this kind of plugins can help quality.

In documentation I see references to **@backstage/plugin-score-card** but in NPM I only see **@oriflame/backstage-plugin-score-card**. Also would be nice in the Readme to have the **yarn add** command.

Then I added the code examples found in Readme (using the @oriflame/backstage-plugin-score-card package) and in app-config.yaml I added

`scorecards:
  jsonDataUrl: https://github.com/Oriflame/backstage-plugins/blob/main/plugins/score-card/sample-data/`

## Expected Behavior

Score card loads the sample data in UI.

## Current Behavior

When I try to reach score cards it get's a CORS issue
![image](https://user-images.githubusercontent.com/2378539/200192844-6d6a3739-bc76-48fd-bc4d-b43c7728d9a8.png)

## Steps to Reproduce

1. Install @oriflame/backstage-plugin-score-card package
2. Follow steps in the Readme.md
3. Add jsonDataUrl the github sample path
4. Go to Score Cards list

I'm running backstage locally

I'm still very new in Backstage and maybe I'm missing some configuration.

**Comment by ruieloi** [comment]
Discard my problem related with the jsonDataUrl. Changed the url to 

https://raw.githubusercontent.com/Oriflame/backstage-plugins/main/plugins/score-card/sample-data/

and works correctly!

**Comment by jvilimek** [comment]
Thanks for the comments/suggestion.
Regards your issue with Json URL: it needs to be added among allowed url too. I will mention this in the documentation.

**Comment by jvilimek** [comment]
I believe I have addressed your issue/feedback. Feel free to comment if not, otherwise I will close this issue in few days.

**Comment by ruieloi** [comment]
Yap it's great! Thank you very much!
Keep up the good work!!
