### ISSUE TITLE
Cant access scorecard data from private github repo

### ISSUE THREAD

**Issue by andrewgkew** [Oriflame/backstage-plugins#111]
Currently the only way the scorecard can access data is via a public repo. Specifying a token in the URL does not work either

Add the ability to specify a token in configuration file or re-use token already configured

Pull scorecard data from private repo

**Comment by jvilimek** [comment]
Thanks for a feedback.

I see you want to have the JSON data with the scores in your private repository. Unfortunately "out of the box" this is not possible as the plugin accesses the data from within the client side (directly from the browser). There is no backend endpoint implemented, that would allow to access private repository (or database).

However it is possible to implement custom [ScoringDataApi](https://github.com/Oriflame/backstage-plugins/blob/main/plugins/score-card/src/api/ScoringDataApi.ts) see e.g. [ScoringDataJsonClient](https://github.com/Oriflame/backstage-plugins/blob/main/plugins/score-card/src/api/ScoringDataJsonClient.ts).

Is this something you want to contribute with?

**Comment by andrewgkew** [comment]
@jvilimek thanks for your comments. Yes I will look into contributing this feature, just a thought, you are getting the jsonDataUrl using the backstage core config API

`this.configApi.getOptionalString('scorecards.jsonDataUrl')`

I assume you should be able to do the same with the github token

`this.configApi.getOptionalString('integrations.github[0].token')`

Then this could be passed into the fetch method as an auth header, I will have to test but that seems like a logical way to do it, otherwise allowing user to specify their own token as part of the scorecard config too would work

I will put this into a private dataAPI class

**Comment by jvilimek** [comment]
Thanks! 

Few thoughts:

> I assume you should be able to do the same with the github token
> 
> `this.configApi.getOptionalString('integrations.github[0].token')`

Unfortunately this config is not exposed to the frontend so this won't return the token..either it will be null or it will fail.

I am afraid a new API client would be needed and this client would need to call some new backend API or [some (new) proxy](https://backstage.io/docs/plugins/proxying).

**Comment by T0RAT0RA** [comment]
Using proxy you can access your private repository data:

```yaml
proxy:
  '/scorecards':
    target: https://raw.githubusercontent.com/<org>/<repo>/<branch>/<path-to-json-files>/
    headers:
      Authorization: 'token ${GITHUB_TOKEN}'

scorecards:
  jsonDataUrl: /api/proxy/scorecards/
```

Now it only works with a GitHub token, if you're using a GitHub app, you'll have to build a backend proxy to retrieve the files with the GitHub app credentials.

**Comment by jvilimek** [comment]
Thanks, @T0RAT0RA, for a nice solution!
@andrewgkew WDYT? Shall we now close the issue?

**Comment by jvilimek** [comment]
@andrewgkew  please re-open in case the proxy solution is not working.

**Comment by andrewgkew** [comment]
@T0RAT0RA thanks for the solution I will give that a go. @jvilimek thanks yes I will give it a whirl and reopen if I have any issues

**Comment by stasOR41k** [comment]
> ```yaml
>     target: https://raw.githubusercontent.com/<org>/<repo>/<branch>/<path-to-json-files>/
> ```

Is this still a working solution?

**Comment by stasOR41k** [comment]
> Using proxy you can access your private repository data:
> 
> ```yaml
> proxy:
>   '/scorecards':
>     target: https://raw.githubusercontent.com/<org>/<repo>/<branch>/<path-to-json-files>/
>     headers:
>       Authorization: 'token ${GITHUB_TOKEN}'
> 
> scorecards:
>   jsonDataUrl: /api/proxy/scorecards/
> ```
> 
> Now it only works with a GitHub token, if you're using a GitHub app, you'll have to build a backend proxy to retrieve the files with the GitHub app credentials.

Is it still a working solution?

**Comment by ninaadlakshman** [comment]
@stasOR41k I'm seeing the same. Unable to pull from the private repository through the proxy. Has anybody had success recently?

I'm guessing things have changed w/ Backstage enough to break this, but I may be setting something wrong.
