### ISSUE TITLE
There is no explicit way to configure a fetch with credentials for a repo

### ISSUE THREAD

**Issue by diegor1vs** [Oriflame/backstage-plugins#150]
I was trying to look for a way to connect the score content file from my personal repo with credentials.

Is it possible? because I could not

**Comment by jvilimek** [comment]
Hi, @diegor1vs, thanks for the question, and sorry it took a long time (I was sick). Have you considered configuring a proxy as suggested here: https://github.com/Oriflame/backstage-plugins/issues/111 ?
