### ISSUE TITLE
(Score card) Make wiki links optional

### ISSUE THREAD

**Issue by sichapman** [Oriflame/backstage-plugins#177]
For people that don't have a need for each standard to link out to somewhere, it would be useful to make this an optional feature

## Possible Implementation

If `wikiLinkTemplate` is not provided, render the title as plain text, not a link

**Comment by jvilimek** [comment]
Thanks for the feedback. Unfortunately, I missed the notification and so, apparently, my colleagues.
It seems like an easy change, hope I get to it soon.

**Comment by T0RAT0RA** [comment]
Hi,
I also need `wikiLinkTemplate` to be optional, I'll take it if nobody has started it.
