### ISSUE TITLE
Release @oriflame/backstage-plugin-score-card 0.6.3 to NPM

### ISSUE THREAD

**Issue by tmclaugh** [Oriflame/backstage-plugins#178]
`package.json` says 0.6.3 but NPM only has version 0.6.2 as latest

## Expected Behavior

0.6.3 is available on NPM

## Current Behavior

0.6.2 is available on NPM

**Comment by jvilimek** [comment]
Thanks for raising this concern. The token for the publish task expired, unfortunately. It's already being solved, but it's taking time :-( I will try to speed it up a bit. Hope to get to you back soon with a good news!

**Comment by jvilimek** [comment]
aaand.. forgot to close this one. Publish is working fine now, currently deployed version 0.7.1
