### ISSUE TITLE
When there are too many components with scores, score card page breaks

### ISSUE THREAD

**Issue by surenraju-careem** [Oriflame/backstage-plugins#184]
When there are too many components with scores, Score card page breaks.

https://github.com/Oriflame/backstage-plugins/blob/main/plugins/score-card/src/api/ScoringDataJsonClient.ts#L106

This query becomes too long.

**Comment by mchiuminatto** [comment]
Anyone reviewing this PR, I've got same issue. from roughly 900 repos, I can list roughly 500 before scoreboard breaks.
