### ISSUE TITLE
update to newer backstage dependencies, to fix `zod` vulnerability 

### ISSUE THREAD

**Issue by freben** [Oriflame/backstage-plugins#203]
## Feature Suggestion

Hello from the Backstage maintainers! I'd like to give a nudge toward migrating the plugins to a newer version of the Backstage framework, if possible.

## Possible Implementation

Migrate the plugins to depending on a newer Backstage version.

## Context

https://github.com/backstage/backstage/issues/21777

Old versions of the Backstage framework depended on a `zod` version range that has since gotten a security report, and there's no fix within that range. Newer Backstage versions do not pull in the vulnerable library. The only remaining dependency in the main Backstage repo that does pull in this library, happens to be the score-card plugin at this point.

Thanks for all of your contributions!

**Comment by jvilimek** [comment]
Hi @freben, sure will update as soon as possible!

**Comment by jvilimek** [comment]
Release of the new package failed as the `yarn workspace` publish task I have replaced previously working `lerna` needs newer Yarn probably. Will fix this later today

**Comment by jvilimek** [comment]
package released: https://www.npmjs.com/package/@oriflame/backstage-plugin-score-card/v/0.8.0
