### ISSUE TITLE
Component Level View with Overall System Score

### ISSUE THREAD

**Issue by regicsolutions** [Oriflame/backstage-plugins#99]
## Feature Suggestion
Love the idea of this plugin, and how everything is pure json 😀

Haven’t had a chance to play with it but looking at the screen prints I am not seeing a component view where I can see the scorecard at the component level when I open a component entity or more importantly when I bring up a system scorecard it would be nice to get a component level view where I have one system with 50 microservices / components I can see the score of each service together with an Overall System Score.

**Comment by regicsolutions** [comment]
That’s correct, having visibility at the component and system level would be ideal, you bring up some great points, i wouldn’t personally restrict it down to the component type, but would consider making the  [EntityScoreCardContent](https://github.com/backstage/backstage/blob/af5d2741da4900310b439d8a0158f3a2e7e5e45f/packages/app/src/components/catalog/EntityPage.tsx#L711) more of a EntityHasScoreCardContent where it’s only displayed if there is content similar to how other plugins are doing it i.e `EntitySwitch.Case if={isScoreCardAvailable}>` 

Regarding requirements by entity kind/type. I would suggest having a entity rules registry like cortex does it where all rules are re-usable across any entity kind/type.

```
entityScoreCardRule: less than 15 Jira issues 
  appliesToKinds: [ ‘Component’,  ‘System’ ]
// Maybe even filtering down to types?
  appliesToTypes: [ ‘service’ , ‘homegrown’ ]
```

Thinking it may make sense to have an overall “average” score as shown below where you bring up a parent entity such as a system entity where the average score is calculated based on all component scores for that system, that can be 1 or hundreds this can continue down the parent/child catalog hierarchy where you can possibly get down to the domain level, that’s when the executives start to drool 🤤 

![F9C5FC11-E42E-434C-B1D2-E50F20E430F4](https://user-images.githubusercontent.com/6157895/201269194-7c6ed87f-4dcc-417b-bf30-b7f358e09e86.png)

**Comment by jvilimek** [comment]
@regicsolutions I am sorry I didn't have time to get back to this. But it makes sense to me to make this plugin more extendable. Is this something you want to contribute with?

**Comment by T0RAT0RA** [comment]
Hi,

I also have the need to score other kind of entities.
Current implementation already allow that, even though there are some assumptions to be a `system` .
For instance, scoring an API:
```diff
const apiPage = (
  <EntityLayout>
    <EntityLayout.Route path="/" title="Overview">
      <Grid container spacing={3}>
        <Grid item md={6}>
          <EntityAboutCard />
        </Grid>
      </Grid>
    </EntityLayout.Route>
+   <EntityLayout.Route path="/score" title="Score">
+     <Grid container spacing={3} alignItems="stretch">
+       <Grid item xs={12}>
+         <EntityScoreCardContent />
+       </Grid>
+     </Grid>
+   </EntityLayout.Route>
  </EntityLayout>
);
```
It will try to find `${jsonDataUrl}/<api-name>.json`.

Now what @jvilimek proposed here https://github.com/Oriflame/backstage-plugins/pull/123#issuecomment-1340658295, to have the `namespace` and `kind` as part of the scorecard path, would make it easier for a backend to identify the entity, and build logic to retrieve its scorecard.

While at it, I would replace the references to `systemEntityName` by  `entity`, and support [Entity References](https://backstage.io/docs/features/software-catalog/references), like:

```json
{
  "entity": "api/foo"
}
```
```json
{
  "entity": "default/api/foo"
}
```
```json
{
  "entity": {
    "kind": "component"
    "name": "abc"
  }
}
```
(with `namespace` being optional)


I would also add a `Kind` (or `Type`) column on the `ScoreCardTable`, for sorting and filter.
It would also be nice to be a property so we kind build different scorecard pages, per entity kind.

If the property Kind is set, it would also be used to fetch the `all.json` file: `${jsonDataUrl}/api/all.sjon`, `${jsonDataUrl}/system/all.json`, falling back to the default `${jsonDataUrl}/all.json` when not set.


I can help with the implementation.

**Comment by regicsolutions** [comment]
> Hi,
> 
> 
> 
> I also have the need to score other kind of entities.
> 
> Current implementation already allow that, even though there are some assumptions to be a `system` .
> 
> For instance, scoring an API:
> 
> ```diff
> 
> const apiPage = (
> 
>   <EntityLayout>
> 
>     <EntityLayout.Route path="/" title="Overview">
> 
>       <Grid container spacing={3}>
> 
>         <Grid item md={6}>
> 
>           <EntityAboutCard />
> 
>         </Grid>
> 
>       </Grid>
> 
>     </EntityLayout.Route>
> 
> +   <EntityLayout.Route path="/score" title="Score">
> 
> +     <Grid container spacing={3} alignItems="stretch">
> 
> +       <Grid item xs={12}>
> 
> +         <EntityScoreCardContent />
> 
> +       </Grid>
> 
> +     </Grid>
> 
> +   </EntityLayout.Route>
> 
>   </EntityLayout>
> 
> );
> 
> ```
> 
> It will try to find `${jsonDataUrl}/<api-name>.json`.
> 
> 
> 
> Now what @jvilimek proposed here https://github.com/Oriflame/backstage-plugins/pull/123#issuecomment-1340658295, to have the `namespace` and `kind` as part of the scorecard path, would make it easier for a backend to identify the entity, and build logic to retrieve its scorecard.
> 
> 
> 
> While at it, I would replace the references to `systemEntityName` by  `entity`, and support [Entity References](https://backstage.io/docs/features/software-catalog/references), like:
> 
> 
> 
> ```json
> 
> {
> 
>   "entity": "api/foo"
> 
> }
> 
> ```
> 
> ```json
> 
> {
> 
>   "entity": "default/api/foo"
> 
> }
> 
> ```
> 
> ```json
> 
> {
> 
>   "entity": {
> 
>     "kind": "component"
> 
>     "name": "abc"
> 
>   }
> 
> }
> 
> ```
> 
> (with `namespace` being optional)
> 
> 
> 
> 
> 
> I would also add a `Kind` (or `Type`) column on the `ScoreCardTable`, for sorting and filter.
> 
> It would also be nice to be a property so we kind build different scorecard pages, per entity kind.
> 
> 
> 
> If the property Kind is set, it would also be used to fetch the `all.json` file: `${jsonDataUrl}/api/all.sjon`, `${jsonDataUrl}/system/all.json`, falling back to the default `${jsonDataUrl}/all.json` when not set.
> 
> 
> 
> 
> 
> I can help with the implementation.

That's great, @jvilimek i am a bit tied up with other initiatives at the moment maybe we can assign this one to @T0RAT0RA for an initial MVP?

**Comment by jvilimek** [comment]
Also, it will be probably a breaking change in terms of storing/providing the data. It would mean a couple of things on our side as well, like adjusting the paths for uploading the scoring results... but not a big deal.

**Comment by jvilimek** [comment]
Thanks a lot!

Thinking of backward compatibility...maybe more calls, but it could be done also like fetching `${jsonDataUrl}/{namespace}/{kind}/{name}.json`, falling to `${jsonDataUrl}/{kind}/{name}.json`, falling back to the old-style `${jsonDataUrl}/{name}.json` .. similar way, how you have proposed the "all.json" fetching...

**Comment by regicsolutions** [comment]
Good to close Thanks @T0RAT0RA
